#@TYPE: Machine
#@NAME: licheepi-zero-dock
#@DESCRIPTION: Machine configuration for the licheepi-zero-dock, based on allwinner V3s CPU

require conf/machine/include/sun8i.inc

UBOOT_MACHINE = "LicheePi_Zero_defconfig"
KERNEL_DEVICETREE_FILE = "sun8i-v3s-licheepi-zero-dock.dtb"
KERNEL_DEVICETREE = "allwinner/${KERNEL_DEVICETREE_FILE}"
IMAGE_BOOT_FILES = "\
    ${KERNEL_IMAGETYPE} \
    boot.scr \
    ${KERNEL_DEVICETREE_FILE} \
"

WKS_FILES = "licheepi-zero-dock.wks"
