# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-licheepi-media"
BBFILE_PATTERN_meta-licheepi-media = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-licheepi-media = "6"

LAYERDEPENDS_meta-licheepi-media = "core"
LAYERSERIES_COMPAT_meta-licheepi-media = "kirkstone"
